apiVersion: v1
kind: Service
metadata:
  name: kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
