apiVersion: v1
kind: Service
metadata:
  name: kubernetes
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kubernetes
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - image: 'paulbouwer/hello-kubernetes:1.8'
          name: kubernetes
          ports:
            - containerPort: 8080

