apiVersion: v1
kind: Service
metadata:
  name: ngnixservice-1
spec:
  ports:
    - nodePort: 31223
      port: 80
      targetPort: 80
  selector:
    app: ngnix
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnixdeployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
        - image: 'nginx:1.16.1'
          name: ngnixcontainer-1
          ports:
            - containerPort: 80
